### PR TITLE
Introduced configurability to work with Chat rooms 

### PR DESCRIPTION
**Pull request by nstielau**
Hey,

I made some changes to introduce some extra configurability that I needed to get this to work with a chat room, specifically http://partychapp.appspot.com/.  The changes are non-intrusive, and should add some useful flexibility.  

The ':startup_message' setting is just for fun, but the ':misunderstood_message' and ':help_regex' are required to get a bot working in the chat room.

Thanks,

-nick

### CODE REVIEW

**Comment by brettstimmerman** [comment]
Hi Nick. Good stuff. 

My only concern is with :help_regex. It might make sense to have a corresponding :help_syntax option to go along with it. The syntax should then also trickle into the misunderstood message. While we're at it, the help alias '?' should probably be configurable, or at least optional.

Out of curiosity, how did adding :help_regex make creating your bot easier?

**Comment by nstielau** [comment]
Hey Brett, thanks for the quick reply.  Partychapp, the psuedoroom I'm using, prepends your usename to your messages, i.e. '[nick.stielau] hey!'.  The default help regex cannot be triggered, as there is always a name up front.  

Thinking more, the only thing that I really need is the 'misunderstood_message' deactivation (so random chatroom chatter doesn't upset the bot).  I agree that the 'help_regex' is a little incomplete without help_syntax etc, but a handful of additional config settings might just be clutter.  Also, the help command can be implemented in the bot itself, calling bot.send(:help_message, sender, message), if need be.  What do you thing about leaving the help_regex changes out?

-nick

**Comment by brettstimmerman** [comment]
Agree that having too many configs is just clutter, but that making the startup and misunderstood messages optional is useful. I'll pick this up later this week, sans :help_regex changes.

**Comment by nstielau** [comment]
Thanks!

I'll get a good blog post out about bots with partychapp once the new
gem is out.

-nick

On Wed, Apr 20, 2011 at 5:40 AM, brettstimmerman
reply@reply.github.com
wrote:

> Agree that having too many configs is just clutter, but that making the startup and misunderstood messages optional is useful. I'll pick this up later this week, sans :help_regex changes.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/brettstimmerman/jabber-bot/pull/2#issuecomment-1032481

## 

Nick Stielau
206-245-7991

**Comment by brettstimmerman** [comment]
I think I fooled github's pull request tracking with rebase -i when removing the :help_regex bits. But, jabber-bot 1.2.0 is published:

gem install jabber-bot

**Comment by nstielau** [comment]
Nice, thanks! I'll check it out.

**Pull request closed without merging**
