### PR TITLE
Fix for individual command helper.

### PR DESCRIPTION
**Pull request by TheLarkInn**
Regex was returning ' <command>' instead of '<command>', therefore preventing the single command help lookup from working.

### CODE REVIEW

**Comment by brettstimmerman** [comment]
Hey @TheLarkInn, nice catch and thanks for the pull request! Would you mind removing the invisible command piece since it's not related?

**Comment by TheLarkInn** [comment]
Oh goodness I'm sorry about that. Yeah let me change that. Might take a moment for me to figure out how to do it! lol

**Comment by TheLarkInn** [comment]
I think I did that right, please let me know if that was wrong. Still a little new to git/github! :)

**Comment by brettstimmerman** [comment]
Sorry for leaving this hanging so long. Thanks again for the pull request.

**Pull request merged**
